from Tkinter import *
from Tkinter import filedialog
window=Tk()
window.geometry('350x200')
window.title("calculator")
#lbl=Label(window, text="hello",font=("times new roman",10))
#lbl.grid(column=1,row=5)
#btn=Button(window,text="click Me")
#btn.grid(column=1,row=0)
btn0=Button(window,text="    0     ",bg="white")
btn0.grid(column=1,row=5)
btn1=Button(window,text="    1     ",bg="white")
btn1.grid(column=1,row=4)
btn2=Button(window,text="    2     ",bg="white")
btn2.grid(column=2,row=4)
btn3=Button(window,text="    3     ",bg="white")
btn3.grid(column=3,row=4)
btn4=Button(window,text="    4     ",bg="white")
btn4.grid(column=1,row=3)
btn5=Button(window,text="    5     ",bg="white")
btn5.grid(column=2,row=3)
btn6=Button(window,text="    6     ",bg="white")
btn6.grid(column=3,row=3)
btn7=Button(window,text="    7     ",bg="white")
btn7.grid(column=1,row=2)
btn8=Button(window,text="    8     ",bg="white")
btn8.grid(column=2,row=2)
btn9=Button(window,text="    9     ",bg="white")
btn9.grid(column=3,row=2)
txt= Entry(window,width=5)
txt.grid(column=1,row=1)
window.mainloop()